import { Invoice } from "@/types/invoice"
import jsPDF from "jspdf"

  export const handleDownloadPDF = (invoice:Invoice) => {
    const doc = new jsPDF({ unit: "pt", format: "a4" })
    const left = 40
    let y = 40
    doc.setFontSize(22)
    doc.text("SolPay Invoice", left, y)
    doc.setFontSize(12)
    y += 30
    doc.text(`Invoice #: ${invoice.id || invoice.invoiceNo}`, left, y)
    y += 18
    doc.text(`Issue Date: ${new Date().toLocaleDateString()}`, left, y)
    if (invoice.dueDate) {
      y += 18
      doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, left, y)
    }
    y += 24
    doc.setFontSize(16)
    doc.text("Bill To:", left, y)
    doc.setFontSize(12)
    y += 18
    doc.text(invoice.clientName || "", left, y)
    y += 16
    doc.text(invoice.clientAddress || "", left, y)
    if (invoice.clientEmail) {
      y += 16
      doc.text(invoice.clientEmail, left, y)
    }
    if (invoice.clientWallet) {
      y += 16
      doc.text(`Wallet: ${invoice.clientWallet}`, left, y)
    }
    y += 24
    doc.setFontSize(16)
    doc.text("Services", left, y)
    y += 18
    doc.setFontSize(12)
    doc.text("Item", left, y)
    doc.text("Qty", left + 200, y)
    doc.text("Price", left + 250, y)
    doc.text("Total", left + 320, y)
    y += 12
    doc.setLineWidth(0.5)
    doc.line(left, y, left + 380, y)
    y += 10
    invoice.services.forEach((service: any) => {
      doc.text(String(service?.name ?? '-'), left, y)
      doc.text(String(service?.quantity ?? '-'), left + 200, y)
      doc.text(String(service?.unitPrice ?? '-'), left + 250, y)
      doc.text(String((service?.quantity ?? 0) * (service?.unitPrice ?? 0)), left + 320, y)
      y += 16
      if (service?.description) {
        doc.setFontSize(10)
        doc.text(String(service.description), left + 10, y)
        doc.setFontSize(12)
        y += 14
      }
    })
    y += 10
    doc.setLineWidth(0.5)
    doc.line(left, y, left + 380, y)
    y += 18
    doc.text(`Subtotal: ${invoice.subtotal}`, left + 250, y)
    y += 16
    doc.text(`Tax (${invoice.taxRate}%): ${invoice.taxAmount}`, left + 250, y)
    y += 16
    doc.setFontSize(14)
    doc.text(`Total: ${invoice.totalAmount} ${invoice.currency || "$"}`, left + 250, y)
    y += 30
    doc.setFontSize(12)
    doc.text("Payment Instructions:", left, y)
    y += 16
    doc.text(`Send payment to: ${invoice.createdBy?.address || "Unknown Wallet Address"}`, left, y)
    y += 16
    doc.text(`Token: ${invoice.currency || "-"}`, left, y)
    if (invoice.isExpirable && invoice.dueDate) {
      y += 16
      doc.text(`Payment due by: ${new Date(invoice.dueDate).toLocaleDateString()}`, left, y)
    }
    y += 30
    doc.setFontSize(10)
    doc.text("Thank you for your business. Payment is expected within the due date of invoice receipt. Please make payment via the provided wallet address.", left, y, { maxWidth: 400 })
    y += 30
    doc.setFontSize(10)
    doc.text("This invoice was generated by SolPay. For questions, contact support@solpay.com", left, y, { maxWidth: 400 })
    doc.save(`invoice-${invoice.id || invoice.invoiceNo}.pdf`)
   
  }
